# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Fazal Hashmi\Desktop\project04.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 292)
        MainWindow.setMinimumSize(QtCore.QSize(677, 292))
        MainWindow.setMaximumSize(QtCore.QSize(677, 292))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Decryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Decryptbtn.setGeometry(QtCore.QRect(540, 230, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Decryptbtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Fazal Hashmi\\Desktop\\../Downloads/decrypt (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Decryptbtn.setIcon(icon)
        self.Decryptbtn.setIconSize(QtCore.QSize(20, 20))
        self.Decryptbtn.setObjectName("Decryptbtn")
        self.Ciphertextbox = QtWidgets.QTextEdit(self.centralwidget)
        self.Ciphertextbox.setGeometry(QtCore.QRect(60, 60, 601, 61))
        self.Ciphertextbox.setObjectName("Ciphertextbox")
        self.Cipherlab = QtWidgets.QLabel(self.centralwidget)
        self.Cipherlab.setGeometry(QtCore.QRect(60, 40, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Cipherlab.setFont(font)
        self.Cipherlab.setObjectName("Cipherlab")
        self.plaintextlab = QtWidgets.QLabel(self.centralwidget)
        self.plaintextlab.setGeometry(QtCore.QRect(60, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plaintextlab.setFont(font)
        self.plaintextlab.setObjectName("plaintextlab")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 0, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Copyrightlab = QtWidgets.QLabel(self.centralwidget)
        self.Copyrightlab.setGeometry(QtCore.QRect(60, 230, 161, 20))
        self.Copyrightlab.setObjectName("Copyrightlab")
        self.Plaintext_textbox = QtWidgets.QTextEdit(self.centralwidget)
        self.Plaintext_textbox.setGeometry(QtCore.QRect(60, 160, 601, 61))
        self.Plaintext_textbox.setObjectName("Plaintext_textbox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Decryptbtn.clicked.connect(self.method_1, )

    def method_1(self):
        ciphertext = self.Ciphertextbox.toPlainText()
        ciphertext = ciphertext.lower()
        size = len(ciphertext)
        dic1 = {
            'o': 'u', 'l': 'n', 'q': 'c', 'i': 'o', 'h': 'm', 'x': 'f', 'r': 'r', 'c': 't', 'k': 'a', 'g': 'b',
            'n': 'l', 'z': ['e', 'y']
        }
        dic2 = {
            'p': ['c', 'i', 'p', 'u'], 'l': ['o', 'n'], 'q': ['n', 'c', 'r', 'i'], 'r': ['v', 'r', 't'], 'z': 'e',
            'b': ['s', 'd']
        }
        dic3 = {
            'm': ['a', 'd'], 'p': ['d', 'i'], 'b': ['m', 's'], 'k': ['i', 'a'], 's': ['t', 'p'], 'i': ['e', 'o'],
            'l': ['l', 'n'], 'c': ['y', 't']
        }
        finaldic = {}
        finaldic1 = {}
        apla = []
        for x, y in dic1.items():
            apla.append(x)

        for x, y in dic2.items():
            apla.append(x)
        for x, y in dic3.items():
            apla.append(x)
        apla.sort()
        apla = list(dict.fromkeys(apla))

        j = 0
        for a in apla:
            count = 0
            x = ''
            y = ''
            z = ''
            # print(x,'y=',y,'z=',z)
            if (a in dic1.keys()):
                x = dic1.get(a)
            if (a in dic2.keys()):
                y = dic2.get(a)
            if (a in dic3.keys()):
                z = dic3.get(a)
            if x != '' and y == '' and z == '':
                temp = x
                if (len(temp) < 4):
                    finaldic[a] = x
            elif x == '' and y != '' and z == '':
                temp = x
                if (len(temp) < 4):
                    finaldic[a] = y
            elif x == '' and y == '' and z != '':
                temp = x
                if (len(temp) < 4):
                    finaldic[a] = z
            elif x != '' and y != '' and z == '':
                temp = x
                temp1 = y
                if (len(temp) >= len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp:
                        n = temp1.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
                elif (len(temp) < len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp1:
                        n = temp.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
            elif x != '' and y == '' and z != '':
                temp = x
                temp1 = z
                if (len(temp) >= len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp:
                        n = temp1.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
                elif (len(temp) < len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp1:
                        n = temp.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
            elif x == '' and y != '' and z != '':
                temp = y
                temp1 = z
                if (len(temp) >= len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp:
                        n = temp1.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
                elif (len(temp) < len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp1:
                        n = temp.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
            elif x != '' and y != '' and z != '':
                temp = x
                temp1 = y
                temp3 = z
                if (len(temp) >= len(temp1) and len(temp) >= len(temp3)):
                    t = ''
                    ct = 0
                    for v in temp:
                        n = temp1.count(v)
                        n = n + temp3.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
                elif (len(temp1) >= len(temp) and len(temp1) >= len(temp3)):
                    t = ''
                    ct = 0
                    for v in temp1:
                        n = temp.count(v)
                        n = n + temp3.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t
                elif (len(temp3) >= len(temp) and len(temp3) >= len(temp1)):
                    t = ''
                    ct = 0
                    for v in temp3:
                        n = temp.count(v)
                        n = n + temp1.count(v)
                        if (n > ct):
                            ct = n
                            t = v
                    finaldic[a] = t

        tempDic = {}
        print(finaldic)
        for d in finaldic.keys():
            if (len(finaldic.get(d))) < 2:
                finaldic1[d] = finaldic.get(d)
            else:
                tempDic[d] = finaldic.get(d)

        print(tempDic)


        for d in tempDic.keys():
            if (len(finaldic[d])) > 1:
                temp = finaldic.get(d)
                for x in temp:
                    if (finaldic1.values()):
                        finaldic1[d] = x
        print(finaldic1)

        plaintext = ''
        for i in range(size):
            char = ciphertext[i]
            if char in finaldic1:
                plaintext = plaintext + finaldic1[char]
            else:
                plaintext = plaintext + ciphertext[i]
        self.Plaintext_textbox.setText(plaintext)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cryptogram Breaker"))
        self.Decryptbtn.setText(_translate("MainWindow", "Decrypt"))
        self.Cipherlab.setText(_translate("MainWindow", "Cipher Text"))
        self.plaintextlab.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Fazal Ur Rehman Hashmi"))
        self.label_4.setText(_translate("MainWindow", "Salman Zulfiqar "))
        self.Copyrightlab.setText(_translate("MainWindow", "© 2021 Fazal Ur Rehman Hashmi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
